import React from "react";
import Head from "next/head";
import LoginPage from "./LoginPage/LoginPage";

const Home: React.FC = () => {
  return (
    <div>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <LoginPage />
      </main>
    </div>
  );
};

export default Home;
